# Generated by Django 5.2.4 on 2025-07-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_comment_options_alter_comment_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='api_comment_created_db28e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='api_comment_product_e87390_idx',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created_at'], name='api_comment_created_d7a6d8_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['owner', 'product'], name='api_comment_owner_i_d1dcbc_idx'),
        ),
    ]
